export const ENTRY_LIST_REQUEST = "ENTRY_LIST_REQUEST";
export const ENTRY_LIST_SUCCESS = "ENTRY_LIST_SUCCESS";
export const ENTRY_LIST_FAIL = "ENTRY_LIST_FAIL";

export const ENTRY_CREATE_REQUEST = "ENTRY_CREATE_REQUEST";
export const ENTRY_CREATE_SUCCESS = "ENTRY_CREATE_SUCCESS";
export const ENTRY_CREATE_FAIL = "ENTRY_CREATE_FAIL";

export const ENTRY_UPDATE_REQUEST = "ENTRY_UPDATE_REQUEST";
export const ENTRY_UPDATE_SUCCESS = "ENTRY_UPDATE_SUCCESS";
export const ENTRY_UPDATE_FAIL = "ENTRY_UPDATE_FAIL";

// export const LAST_ENTRY_REQUEST = "LAST_ENTRY_REQUEST";
// export const LAST_ENTRY_SUCCESS = "LAST_ENTRY_SUCCESS";
// export const LAST_ENTRY_FAIL = "LAST_ENTRY_FAIL";

export const STATS_REQUEST = "STATS_REQUEST";
export const STATS_SUCCESS = "STATS_SUCCESS";
export const STATS_FAIL = "STATS_FAIL";

export const TAGS_STATS_REQUEST = "TAGS_STATS_REQUEST";
export const TAGS_STATS_SUCCESS = "TAGS_STATS_SUCCESS";
export const TAGS_STATS_FAIL = "TAGS_STATS_FAIL";
