export const FOROMESSAGE_LIST_REQUEST = "FOROMESSAGE_LIST_REQUEST";
export const FOROMESSAGE_LIST_SUCCESS = "FOROMESSAGE_LIST_SUCCESS";
export const FOROMESSAGE_LIST_FAIL = "FOROMESSAGE_LIST_FAIL";

export const FOROMESSAGE_CREATE_REQUEST = "FOROMESSAGE_CREATE_REQUEST";
export const FOROMESSAGE_CREATE_SUCCESS = "FOROMESSAGE_CREATE_SUCCESS";
export const FOROMESSAGE_CREATE_FAIL = "FOROMESSAGE_CREATE_FAIL";