export const FOROMESSAGEVIVENCIA_LIST_REQUEST = "FOROMESSAGEVIVENCIA_LIST_REQUEST";
export const FOROMESSAGEVIVENCIA_LIST_SUCCESS = "FOROMESSAGEVIVENCIA_LIST_SUCCESS";
export const FOROMESSAGEVIVENCIA_LIST_FAIL = "FOROMESSAGEVIVENCIA_LIST_FAIL";

export const FOROMESSAGEVIVENCIA_CREATE_REQUEST = "FOROMESSAGEVIVENCIA_CREATE_REQUEST";
export const FOROMESSAGEVIVENCIA_CREATE_SUCCESS = "FOROMESSAGEVIVENCIA_CREATE_SUCCESS";
export const FOROMESSAGEVIVENCIA_CREATE_FAIL = "FOROMESSAGEVIVENCIA_CREATE_FAIL";