export const FOROMESSAGEHOBBIE_LIST_REQUEST = "FOROMESSAGEHOBBIE_LIST_REQUEST";
export const FOROMESSAGEHOBBIE_LIST_SUCCESS = "FOROMESSAGEHOBBIE_LIST_SUCCESS";
export const FOROMESSAGEHOBBIE_LIST_FAIL = "FOROMESSAGEHOBBIE_LIST_FAIL";

export const FOROMESSAGEHOBBIE_CREATE_REQUEST = "FOROMESSAGEHOBBIE_CREATE_REQUEST";
export const FOROMESSAGEHOBBIE_CREATE_SUCCESS = "FOROMESSAGEHOBBIE_CREATE_SUCCESS";
export const FOROMESSAGEHOBBIE_CREATE_FAIL = "FOROMESSAGEHOBBIE_CREATE_FAIL";