export const CREATE_LECTURE_REQUEST = "CREATE_LECTURE_REQUEST";
export const CREATE_LECTURE_SUCCESS = "CREATE_LECTURE_SUCCESS";
export const CREATE_LECTURE_FAIL = "CREATE_LECTURE_FAIL";

export const LIST_PUBLICATED_LECTURES_REQUEST =
  "LIST_PUBLICATED_LECTURES_REQUEST";
export const LIST_PUBLICATED_LECTURES_SUCCESS =
  "LIST_PUBLICATED_LECTURES_SUCCESS";
export const LIST_PUBLICATED_LECTURES_FAIL = "LIST_PUBLICATED_LECTURES_FAIL";

export const LIST_NON_PUBLICATED_LECTURES_REQUEST =
  "LIST_NON_PUBLICATED_LECTURES_REQUEST";
export const LIST_NON_PUBLICATED_LECTURES_SUCCESS =
  "LIST_NON_PUBLICATED_LECTURES_SUCCESS";
export const LIST_NON_PUBLICATED_LECTURES_FAIL =
  "LIST_NON_PUBLICATED_LECTURES_FAIL";

export const UPDATE_LECTURE_REQUEST = "UPDATE_LECTURE_REQUEST";
export const UPDATE_LECTURE_SUCCESS = "UPDATE_LECTURE_SUCCESS";
export const UPDATE_LECTURE_FAIL = "UPDATE_LECTURE_FAIL";
