export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_UPDATE_FAIL = "USER_UPDATE_FAIL";

export const USER_SECURITY_REQUEST = "USER_SECURITY_REQUEST";
export const USER_SECURITY_SUCCESS = "USER_SECURITY_SUCCESS";
export const USER_SECURITY_FAIL = "USER_SECURITY_FAIL";

export const USER_NOSECURITY_REQUEST = "USER_NOSECURITY_REQUEST";
export const USER_NOSECURITY_SUCCESS = "USER_NOSECURITY_SUCCESS";
export const USER_NOSECURITY_FAIL = "USER_NOSECURITY_FAIL";

export const USER_SETTAGS_REQUEST = "USER_SETTAGS_REQUEST";
export const USER_SETTAGS_SUCCESS = "USER_SETTAGS_SUCCESS";
export const USER_SETTAGS_FAIL = "USER_SETTAGS_FAIL";

export const USER_DIARY_REQUEST = "USER_DIARY_REQUEST";
export const USER_DIARY_SUCCESS = "USER_DIARY_SUCCESS";
export const USER_DIARY_FAIL = "USER_DIARY_FAIL";

export const GET_USERS_REQUEST = "GET_USERS_REQUEST";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAIL = "GET_USERS_FAIL";
